apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
spec:
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: 154100284802.dkr.ecr.us-east-1.amazonaws.com/java_jenkins:latest
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: javaapp-svc
spec:
  selector:
    app: javaapp
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
